# FIXME_KD: remove all comments and make gemfile clean. Always specify gem version.
# Fixed
source 'http://rubygems.org'
gem 'rails', '4.0.0'

gem 'mysql2', '~> 0.3.13'

gem 'sass-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails', '~> 3.0.4'

gem "jquery-ui-rails", '~> 4.0.4'

gem 'jbuilder', '~> 1.2'

gem 'date_validator', '~> 0.7.0'

gem "therubyracer", '~> 0.11.4'
gem "less-rails", '~> 2.3.3'
gem "twitter-bootstrap-rails", '~> 2.2.8'

gem 'gon', '~> 4.1.1'

gem 'permanent_records', '~> 3.1.6'
group :doc do
  gem 'sdoc', '~> 0.3.20'
end

gem 'omniauth', '~> 1.1.4'
gem 'omniauth-google-apps'
# gem 'oauth2', '~> 0.9.2'

gem 'capistrano', '~> 2.0'

# FIXME_KD: No need of this, you can add your own regex to validate.
# Fixed

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'debugger', '~> 1.6.3'
end

gem "factory_girl_rails", "~> 4.0"
gem 'database_cleaner', '~> 1.2.0'
gem 'backup', '~> 3.0.27'
gem 'whenever', '~> 0.9.0'
gem 'fog', ' ~> 1.4.0'
gem 'parallel', '~> 0.5.12'