# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &development
  adapter: mysql2
  encoding: utf8
  database: ham_development
  pool: 5
  username: root
  password: vinsol123
  socket: /var/run/mysqld/mysqld.sock

test:
  <<:  *development
  database: ham_test

production:
  <<:  *development
  database: ham_production

staging: 
  <<:  *development